### ISSUE TITLE
`binder` Frontmatter field is ignored by thebe

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/myst-theme#504]
Right now, it's not easy to specify a custom mybinder URL, e.g. the obvious:
```yaml
version: 1
project:
  binder: https://binder.opensci.2i2c.cloud/
  github: https://github.com/2i2c-org/demo-icepyx
```

Instead, we have to write:
```yaml
version: 1
project:
  jupyter:
    binder:
      repo: https://github.com/2i2c-org/demo-icepyx
      url: https://binder.opensci.2i2c.cloud/

  github: https://github.com/2i2c-org/demo-icepyx
```

This seems to be because we don't listen (at all?) to the `project.binder` Frontmatter entry for anything.
