### ISSUE TITLE
Frontmatter block does not use grid layout in book-theme

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/myst-theme#526]
I'm exploring changing the default grid column for a custom theme route (`_index` for landing pages). When moving from `body` to `page`, I noticed that the front-matter block does not respond to the changed layout:
```css
  .article-grid > *,
  .article-left-grid > *,
  .article-center-grid > * {
    grid-column: page;
  }
``` 

I'm not yet familiar with the grid layout system to know whether e.g. I should just be building a custom grid for the landing page rather than changing the grid column, but this _feels_ like a reasonable vehicle for implementing this feature. 

I suspect the fix is to take the same conditional styling logic from the `ContentBlocks` component: https://github.com/jupyter-book/myst-theme/blob/de028cdf196389f03da41b3fdc0820eefcdfa9e8/packages/site/src/components/ContentBlocks.tsx#L24-L25

Except, there's no obvious mechanism to specify a custom className here.
